name: Deploy Docs with Docusaurus CLI

on:
  # Trigger on pushes to main branch
  push:
    branches:
      - main
    paths:
      - 'docs/**'
      - '.github/workflows/deploy-docs-docusaurus.yml'
  
  # Allow manual trigger
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        working-directory: ./docs
        run: npm install

      - name: Configure Git
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

      - name: Deploy to GitHub Pages
        working-directory: ./docs
        env:
          USE_SSH: false
          GIT_USER: git
          DEPLOYMENT_BRANCH: gh-pages
        run: |
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git
          npm run deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}